//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CargoDataBase : DbContext
    {
        public CargoDataBase()
            : base("name=CargoDataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Orders>()
                .HasMany(o => o.Products)
                .WithMany(p => p.Orders)
                .Map(po =>
                {
                    po.ToTable("Order_product");
                    po.MapLeftKey("product_id");
                    po.MapRightKey("order_id");
                });
        }
    
        public virtual DbSet<Invoice_type> Invoice_type { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<Product_type> Product_type { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Shipp_history> Shipp_history { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
    }
}
