//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int id_invoice { get; set; }
        public Nullable<int> id_invoice_type { get; set; }
        public Nullable<int> id_order { get; set; }
    
        public virtual Invoice_type Invoice_type { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
